package com.hawolt.virtual.client;

/**
 * Created: 23/08/2023 11:46
 * Author: Twitter @hawolt
 **/

public enum LoginState {
    EXTRACT_RIOT_CLIENT_TOKEN, FETCH_RIOT_CLIENT_LOGIN_TOKEN, FETCH_2FA_CODE, RETURN_2FA_CODE, SUBMIT_2FA, FETCH_CAPTCHA_INFO, DELETE_LOGIN_CALL, SOLVE_CAPTCHA, LEAGUE_COOKIE, FETCH_RIOT_CLIENT_COOKIE, OAUTH_TOKEN;
}
